### ISSUE TITLE
打印样式问题

### ISSUE THREAD

**Issue by Yoimiya-993** [Alessandro-Pang/vue-print-next#9]
为什么浏览器弹出的打印窗口第一页纸会有灰色的背景色
![image](https://github.com/user-attachments/assets/77ada169-055a-40db-83f9-6bd49f688d7d)
是继承到body的样式了吗？
![image](https://github.com/user-attachments/assets/692c925d-a4b6-47e8-b98b-64b940a5e20e)
那为什么从第二页纸开始就没有这个背景色了

**Comment by Alessandro-Pang** [comment]
## 样式问题

1. 首先是因为继承到 `body` 的样式了。
> 因为局部打印的原理就是将当前页面所依赖的所有 css 文件全部加载，以此保证样式一致，因此会产生这个问题。
2. 但是 `print` 本身默认是不会打印背景色的，所以 `VuePrintNext` 内置了这个样式：
```css
body {
   -webkit-print-color-adjust: exact;
   -moz-print-color-adjust: exact; 
   -ms-print-color-adjust: exact; 
   print-color-adjust: exact;
}
```
它会使打印时有背景色，但是这个 css 也不能解决所有问题，就比如你遇到的这个问题，分页时背景色没有。

如果想要分页时也有背景色，需要用户手动修改打印的设置，在【更多设置】里，勾选【背景和图形】：

<img width="750" alt="image" src="https://github.com/user-attachments/assets/1a4276b5-06ea-43d0-8113-fabb407af83e">

## 取消样式

目前没有提供不添加 `print-color-adjust` 属性的配置（后面会考虑加进去），所以需要去掉样式只有两种方式：

1. 去掉 body 的背景色
2. 给 body 设置以下样式：

```css
  -webkit-print-color-adjust: unset !important;
  -moz-print-color-adjust: unset !important;
  -ms-print-color-adjust: unset !important;
  print-color-adjust: unset !important;
```
